---
- name: Installer les features AD-Domain-Services et DNS
  ansible.windows.win_feature:
    name:
      - AD-Domain-Services
      - DNS
      - RSAT-ADDS
      - RSAT-DNS-Server
    state: present
    include_management_tools: true
  register: feature_install

- name: Afficher si un redémarrage est nécessaire
  ansible.builtin.debug:
    msg: "Redémarrage requis : {{ feature_install.reboot_required }}"